package be.cm.security;

public enum Feature {
    VIEW_ORDER_REPORTS,
    VIEW_ITEM_SHIPPING_TODAY,
    ORDER_ITEM,
    ADD_ITEM,
    UPDATE_ITEM,
    REORDER_ORDER,
    VIEW_ALL_CUSTOMERS,
    VIEW_A_CUSTOMER,
    GET_ITEM_OVERVIEW
}
